# Generated by Django 2.1 on 2018-08-23 07:33

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_name', models.CharField(max_length=50)),
                ('intro', models.CharField(max_length=200)),
                ('about', models.CharField(max_length=1000)),
                ('password', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Blogs',
            fields=[
                ('blog_id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='BLOG_ID')),
                ('title', models.CharField(max_length=500)),
                ('category', models.CharField(max_length=50)),
                ('created_on', models.DateTimeField(default=datetime.datetime.now)),
                ('updated_on', models.DateTimeField(default=datetime.datetime.now)),
                ('likes', models.IntegerField()),
                ('dislikes', models.IntegerField()),
                ('time_to_read', models.TimeField()),
                ('tags', models.CharField(max_length=500)),
                ('author_id', models.ForeignKey(max_length=50, on_delete=django.db.models.deletion.CASCADE, to='blogs.Author')),
            ],
        ),
    ]
