# Generated by Django 2.1 on 2018-08-28 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogs',
            name='time_to_read',
            field=models.IntegerField(default=0),
        ),
    ]
