# Generated by Django 2.1 on 2018-08-29 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0002_auto_20180828_0628'),
    ]

    operations = [
        migrations.RenameField(
            model_name='author',
            old_name='author_fname',
            new_name='nick_name',
        ),
        migrations.RemoveField(
            model_name='author',
            name='author_lname',
        ),
        migrations.AddField(
            model_name='author',
            name='email',
            field=models.EmailField(default='abc@xyz.com', max_length=50),
            preserve_default=False,
        ),
    ]
