# Generated by Django 2.1 on 2018-08-30 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0003_auto_20180829_0719'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='can_blog',
            field=models.BooleanField(default=False),
        ),
    ]
