# Generated by Django 2.1 on 2018-08-24 16:26

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('blogs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tutorials',
            fields=[
                ('tut_id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='BLOG_ID')),
                ('title', models.CharField(max_length=500)),
                ('category', models.CharField(max_length=50)),
                ('created_on', models.DateTimeField(default=datetime.datetime.now)),
                ('updated_on', models.DateTimeField(default=datetime.datetime.now)),
                ('likes', models.IntegerField()),
                ('dislikes', models.IntegerField()),
                ('time_to_read', models.TimeField()),
                ('tags', models.CharField(max_length=500)),
                ('author_id', models.ForeignKey(max_length=50, on_delete=django.db.models.deletion.CASCADE, to='blogs.Author')),
            ],
        ),
    ]
