# Generated by Django 2.1 on 2018-08-28 06:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0002_auto_20180828_0628'),
        ('tutorials', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tutorials',
            name='author_id',
        ),
        migrations.AddField(
            model_name='tutorials',
            name='author',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='blogs.Author'),
            preserve_default=False,
        ),
    ]
